[phases.setup]
nixPkgs = ['nodejs-18_x', 'python311']

[phases.build]
cmds = [
  'cd web && rm -rf node_modules && npm ci && npm run build && cd ..',
  'pip install -r requirements.txt'
]

[start]
cmd = 'python start.py'
